/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uv.fei.gestionescolar.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import uv.fei.gestionescolar.bussinesslogic.UsuarioDAO;
import uv.fei.gestionescolar.domain.Usuario;
import uv.fei.gestionescolar.validaciones.ValidacionDeDatosRegistro;

/**
 *
 * @author oscar
 */
public class InicioSesionGUI extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesionGUI
     */
    public InicioSesionGUI() {
        initComponents();
    }
        private boolean verificarCampos(String usuario, String constraseña)  {
        ValidacionDeDatosRegistro validar = new ValidacionDeDatosRegistro();
        boolean estatusCampus = false;
        int numeroDeCamposInvalidos = 0;
        if (usuario.isEmpty() || constraseña.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se puede dejar campos en blanco. Campos obligatorios");
        }else{
            if(validar.validarUsuario(usuario) == false) {
                JOptionPane.showMessageDialog(null, "Carácteres inválidos");
                numeroDeCamposInvalidos++;
            }

            if (validar.validarContraseña(constraseña) == false) {
                numeroDeCamposInvalidos++;
            }
            if (numeroDeCamposInvalidos == 0){
                estatusCampus = true;
            }
        }
        return estatusCampus;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInicioSesion = new javax.swing.JLabel();
        lbGestionEscolar = new javax.swing.JLabel();
        tfNombreUsuario = new javax.swing.JTextField();
        lbNombreUsuario = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();
        lbRegistrateAhora = new javax.swing.JLabel();
        lbSinCuenta = new javax.swing.JLabel();
        lbAlumno = new javax.swing.JLabel();
        lbAcademico = new javax.swing.JLabel();
        lbO = new javax.swing.JLabel();
        pfContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbInicioSesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbInicioSesion.setText("Inicio de Sesión");

        lbGestionEscolar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbGestionEscolar.setText("Sistema De Gestión Escolar");

        lbNombreUsuario.setText("Nombre de Usuario");

        lbContraseña.setText("Contraseña");

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        lbRegistrateAhora.setText("Registrate ahora como");

        lbSinCuenta.setText("¿No tienes cuenta?");

        lbAlumno.setText("alumno");
        lbAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAlumnoMouseClicked(evt);
            }
        });

        lbAcademico.setText("académico");
        lbAcademico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAcademicoMouseClicked(evt);
            }
        });

        lbO.setText("o");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcceder)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSinCuenta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbRegistrateAhora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAcademico))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbGestionEscolar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lbInicioSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombreUsuario)
                            .addComponent(lbContraseña)
                            .addComponent(tfNombreUsuario)
                            .addComponent(pfContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbGestionEscolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInicioSesion)
                .addGap(21, 21, 21)
                .addComponent(lbNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAcceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegistrateAhora)
                    .addComponent(lbAlumno)
                    .addComponent(lbAcademico)
                    .addComponent(lbO))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        String nombreUsuario = tfNombreUsuario.getText();
        String contraseña = String.valueOf(pfContraseña.getPassword());
        if(verificarCampos(nombreUsuario, String.valueOf(pfContraseña.getPassword())) == true){
            Usuario usuarioIngresado = new Usuario();
            usuarioIngresado.setNombreDeUsuario(nombreUsuario);
            usuarioIngresado.setContraseña(contraseña);
            Usuario usuarioEncontrado = new Usuario();
            boolean coinciden = false;
            try {
                UsuarioDAO usuarioDao = new UsuarioDAO();
                usuarioEncontrado = usuarioDao.obtenerUsuarioPorNombreDeUsuarioYContraseña(nombreUsuario, contraseña);
                if (usuarioEncontrado != null) {
                    JOptionPane.showMessageDialog(null, "Bienvenido");
                    ConsultarEEGUI consultarEE = new ConsultarEEGUI(usuarioEncontrado);
                    this.setVisible(false);
                    consultarEE.setVisible(true);
                }else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
                }
            } catch (SQLException mensajeError) {
                JOptionPane.showMessageDialog(null, mensajeError.getMessage());
            }
        }               
    }//GEN-LAST:event_btnAccederActionPerformed

    private void lbAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAlumnoMouseClicked
       RegistrarAlumnoGUI registrarAlumno = new RegistrarAlumnoGUI();
       this.setVisible(false);
       registrarAlumno.setVisible(true);
    }//GEN-LAST:event_lbAlumnoMouseClicked

    private void lbAcademicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAcademicoMouseClicked
       RegistrarAcademicoGUI registrarAcademico = new RegistrarAcademicoGUI();
       this.setVisible(false);
       registrarAcademico.setVisible(true);
    }//GEN-LAST:event_lbAcademicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JLabel lbAcademico;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbGestionEscolar;
    private javax.swing.JLabel lbInicioSesion;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbO;
    private javax.swing.JLabel lbRegistrateAhora;
    private javax.swing.JLabel lbSinCuenta;
    private javax.swing.JPasswordField pfContraseña;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
